language: python

python:
  - "3.4"

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq gcc-4.8 g++-4.8 libboost-python-dev
  - cd cryptopp-python-binding
  - CC=g++-4.8 python setup.py install
  - cd ..

before_script:
  - cd ./zpr
  - python manage.py makemigrations
  - python manage.py migrate

script:
  - pytest
